
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class IssueBook extends javax.swing.JInternalFrame {
    Connect con=new Connect();
    ResultSet rs;
    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
       
        initComponents();
        this.setLocation(200, 25);
    }
    //search button books**********************************************************************************************
    public void serch1(){    
        try{
             String query="select * from book where Accno='"+jtxtAccno.getText()+"'";
            rs=con.getQuery(query);
            if(rs.next()){
                String add2=rs.getString("Bname");
                jtxtname1.setText(add2);
                String add3=rs.getString("Bedition");
                jtxtedi.setText(add3);
                String add4=rs.getString("Bpublisher");
                jtxtpub.setText(add4);
                String add5=rs.getString("Bsection");
                jtxtSection.setText(add5);
                String add6=rs.getString("Bpages");
                jtxtpages.setText(add6);
                rs.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "The book id not found");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();

            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        
        
    }
    //search button student--------------------------------------------------------------------------------------------
    public void search2(){
           try{
            String query="select * from student where regno='"+jtxtID.getText()+"'";
            rs=con.getQuery(query);
            if(rs.next()){
                String add2=rs.getString("sname");
                jtxtname.setText(add2);
                String add3=rs.getString("sbatch");
                jtxtbatch.setText(add3);
                String add4=rs.getString("sdep");
                jtxtdep.setText(add4);
                String add5=rs.getString("semail");
                jtxtemail.setText(add5);
                String add6=rs.getString("sphonenumber");
                jtxtcontactno.setText(add6);
                String add7=rs.getString("image");
                lblImage.setIcon(ResizeImage2(add7));
                rs.close();
            }
            else{
                JOptionPane.showMessageDialog(null, "The student's register number not found");
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();

            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }
      public ImageIcon ResizeImage2(String imgPath){
        ImageIcon myImage=new ImageIcon(imgPath);
        Image img=myImage.getImage();
        Image newImage=img.getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImage);
        return image;
    }
    //clear button//////////////////////////////////////////////////////////////////////////////////////
    public void clear2(){
        jtxtID.setText("");
        jtxtname.setText("");
        jtxtbatch.setText("");
        jtxtdep.setText("");
        jtxtemail.setText("");
        jtxtcontactno.setText("");
        jtxtAccno.setText("");
        jtxtname1.setText("");
        jtxtedi.setText("");
        jtxtpub.setText("");
        jtxtSection.setText("");
        jtxtpages.setText("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Year4 = new javax.swing.JLabel();
        Year5 = new javax.swing.JLabel();
        Year6 = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtbatch = new javax.swing.JTextField();
        jtxtdep = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jtxtcontactno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtpages = new javax.swing.JTextField();
        jtxtSection = new javax.swing.JTextField();
        jtxtpub = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtedi = new javax.swing.JTextField();
        jtxtname1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtAccno = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblImage = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("IssueBook");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Batch");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        Year4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Year4.setText("Department");
        jPanel4.add(Year4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Year5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Year5.setText("Email");
        jPanel4.add(Year5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Year6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Year6.setText("Contact No");
        jPanel4.add(Year6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jtxtID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtIDKeyReleased(evt);
            }
        });
        jPanel4.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 170, -1));

        jtxtname.setEditable(false);
        jtxtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, -1));

        jtxtbatch.setEditable(false);
        jtxtbatch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtbatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, -1));

        jtxtdep.setEditable(false);
        jtxtdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, -1));

        jtxtemail.setEditable(false);
        jtxtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, -1));

        jtxtcontactno.setEditable(false);
        jtxtcontactno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 210, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Pages");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Section");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jtxtpages.setEditable(false);
        jtxtpages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 210, -1));

        jtxtSection.setEditable(false);
        jtxtSection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 210, -1));

        jtxtpub.setEditable(false);
        jtxtpub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Publisher");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Edition");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jtxtedi.setEditable(false);
        jtxtedi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 210, -1));

        jtxtname1.setEditable(false);
        jtxtname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(jtxtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Name");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Acc. No");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jtxtAccno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtAccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtAccnoKeyReleased(evt);
            }
        });
        jPanel4.add(jtxtAccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_icon-101-folder-search_314467 (2).png"))); // NOI18N
        jButton5.setToolTipText("Search");
        jButton5.setMaximumSize(new java.awt.Dimension(25, 25));
        jButton5.setMinimumSize(new java.awt.Dimension(25, 25));
        jButton5.setPreferredSize(new java.awt.Dimension(25, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("AcceptableDate");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 130, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Issue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 80, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_icon-101-folder-search_314467 (2).png"))); // NOI18N
        jButton4.setToolTipText("Search");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 50, -1));

        jDateChooser2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDateChooser2KeyReleased(evt);
            }
        });
        jPanel4.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 190, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date of Issue");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 110, -1));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 190, -1));

        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 290, 240));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Issue button%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jtxtID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No student's details to book issue");
            return ;
        }
        if(jtxtAccno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No book's details to book issue");
            return ;
        }
        try{
            jDateChooser2.setDateFormatString("yyyy/MM/dd");
            jDateChooser1.setDateFormatString("yyyy/MM/dd");
            
            String query="insert into issuebook(SRegno,BName,SName,BPublisher,BEdition,Bpages,Accno,BSection,SBatch,SDepartment,SEmail,STelNo,ReturnDate,Issuedate) values('"+jtxtID.getText()
            +"','"+jtxtname1.getText()
            +"','"+jtxtname.getText()
            +"','"+jtxtpub.getText()
            +"','"+jtxtedi.getText()
            +"','"+jtxtpages.getText()
            +"','"+jtxtAccno.getText()
            +"','"+jtxtSection.getText()
            +"','"+jtxtbatch.getText()
            +"','"+jtxtdep.getText()
            +"','"+jtxtemail.getText()
            +"','"+ jtxtcontactno.getText()
            +"','"+((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText()
            +"','"+((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText()
            +"') ";
            int genid=con.setQuery(query, "");

            JOptionPane.showMessageDialog(null,"The Book Issued");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        clear2();
        dashboard x=new dashboard();
        x.calEmail();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      serch1();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        search2();
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIDKeyReleased
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        search2();
        jtxtAccno.requestFocus();
         
     }
    }//GEN-LAST:event_jtxtIDKeyReleased

    private void jtxtAccnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAccnoKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
         serch1();     
     }
    }//GEN-LAST:event_jtxtAccnoKeyReleased

    private void jDateChooser2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser2KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_jDateChooser2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Year4;
    private javax.swing.JLabel Year5;
    private javax.swing.JLabel Year6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtxtAccno;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtSection;
    private javax.swing.JTextField jtxtbatch;
    private javax.swing.JTextField jtxtcontactno;
    private javax.swing.JTextField jtxtdep;
    private javax.swing.JTextField jtxtedi;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtname1;
    private javax.swing.JTextField jtxtpages;
    private javax.swing.JTextField jtxtpub;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
