
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class ManageStudent extends javax.swing.JInternalFrame {
    ResultSet rs;
    String imgPath;
    String imgPath2;
    DefaultTableModel dtm;
    
    /**
     * Creates new form ManageStudent
     */
    public ManageStudent() {
        initComponents();
        jtxtId.setText("EUSLTCIS");
        this.setLocation(150, 50);
        JTable1();
    }
    // clear the insert form details$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    public void clear(){ 
        jtxtId.setText("EUSLTCIS");
        jtxtName.setText("");
        jComboBatch.setSelectedIndex(0);
        jComboDepartment.setSelectedIndex(0);
        jtxtdep.setText("");
        jtxtEmail.setText("");
        jtxtContact.setText("");
    }
    // clear the update form details$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    public void clear2(){ 
        jtxtname.setText("");
        jtxtbatch.setText("");
        jtxtdep.setText("");
        jtxtemail.setText("");
        jtxtcontactno.setText("");
        jLabel11.setIcon(null);
    }
    
    // load the  details to table $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    public void JTable1(){
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
       
         try{
            Connect con=new Connect();
            String query="select * from student";
            
            rs=con.getQuery(query);
           while(rs.next()){
            String regno=rs.getString("regno");
            String sname=rs.getString("sname");
            String sbatch=rs.getString("sbatch");
            String sdep=rs.getString("sdep");
            String semail=rs.getString("semail");
            String sphonenumber=rs.getString("sphonenumber");
               
            dtm.addRow(new Object[]{regno,sname,sbatch,sdep,semail,sphonenumber});
            }
            
            
           }catch(SQLException e){
              JOptionPane.showMessageDialog(null, e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Year = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtId = new javax.swing.JTextField();
        Year1 = new javax.swing.JLabel();
        Year2 = new javax.swing.JLabel();
        jtxtContact = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBatch = new javax.swing.JComboBox<>();
        jComboDepartment = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Year4 = new javax.swing.JLabel();
        Year5 = new javax.swing.JLabel();
        Year6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtbatch = new javax.swing.JTextField();
        jtxtdep = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jtxtcontactno = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jtxtSearchName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtSearchId = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtSearchDep = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setResizable(true);
        setTitle("ManageStudents");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Image");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Batch");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        Year.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Year.setText("Department");
        jPanel1.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jtxtName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, -1));

        jtxtId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 260, -1));

        Year1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Year1.setText("Contact No");
        jPanel1.add(Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        Year2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Year2.setText("Email");
        jPanel1.add(Year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jtxtContact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtContactActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, -1));

        jtxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 30));

        jComboBatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Batch", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel1.add(jComboBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, -1));

        jComboDepartment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Computer Science", "Physical Science", "Language and Comunication", "Business Managment", "Sidda Medicine" }));
        jPanel1.add(jComboDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 230, 220));

        jTabbedPane1.addTab("Add Students", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Batch");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        Year4.setBackground(new java.awt.Color(0, 0, 0));
        Year4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year4.setText("Department");
        jPanel4.add(Year4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Year5.setBackground(new java.awt.Color(0, 0, 0));
        Year5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year5.setText("Email");
        jPanel4.add(Year5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        Year6.setBackground(new java.awt.Color(0, 0, 0));
        Year6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Year6.setText("Contact No");
        jPanel4.add(Year6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_icon-101-folder-search_314467 (3).png"))); // NOI18N
        jButton4.setToolTipText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 30));

        jtxtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIDActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, -1));

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 250, -1));

        jtxtbatch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jtxtbatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, -1));

        jtxtdep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jtxtdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, -1));

        jtxtemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 250, -1));

        jtxtcontactno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(jtxtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, 30));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 300, 80, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Image");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_student-male_2785939 (2).png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 210, 180));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jTabbedPane1.addTab("Edit Sudents", jPanel4);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Student Name", "Batch", "Department", "Email", "Contact No"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Student Id");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Student Name");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Batch");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Department");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Email");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Contact No");
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 650, 300));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Name");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtxtSearchName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchNameKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("St. Id");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jtxtSearchId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchIdKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Dep.");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jtxtSearchDep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchDepActionPerformed(evt);
            }
        });
        jtxtSearchDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchDepKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 150, 30));

        jButton11.setBackground(new java.awt.Color(204, 204, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, -1));

        jTabbedPane1.addTab("Search Student", jPanel7);

        jPanel5.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 410));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        setBounds(0, 0, 711, 462);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
      
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed

    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jtxtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtContactActionPerformed

    }//GEN-LAST:event_jtxtContactActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed

    }//GEN-LAST:event_jtxtEmailActionPerformed
//insert the students details to form@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connect con=new Connect();
        try {
            if(jtxtName.getText().equals("")||jtxtEmail.getText().equals("")|| jtxtContact.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Fill the Every Details");
                return;
            }
            String query="insert into student(regno,sname,sbatch,sdep,semail,sphonenumber,image)  values('"+jtxtId.getText()
                    +"','"+jtxtName.getText()
                    +"','"+jComboBatch.getSelectedItem()
                    +"','"+jComboDepartment.getSelectedItem()
                    +"','"+jtxtEmail.getText()
                    +"','"+jtxtContact.getText()
                    +"','"+imgPath
                    +"')";
            con.setQuery(query);
            // pst.executeQuery();
            JOptionPane.showMessageDialog(null, "New Student registered");
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null,"A Student id have already Registerd");
        }
        JTable1();
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed
   // reset button@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jtxtId.setText("EUSLTCIS");
        jtxtName.setText("");
        jtxtEmail.setText("");
        jtxtContact.setText("");
        jComboBatch.setSelectedIndex(0);
        jComboDepartment.setSelectedIndex(0);
        jLabel9.setIcon(null);

    }//GEN-LAST:event_jButton2ActionPerformed
     
   //Search booton on update form^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String query="select * from student where regno='"+jtxtID.getText()+"'";
        try{
            Connect con=new Connect();
            rs=con.getQuery(query);
            if(rs.next()){
                String add2=rs.getString("sname");
                jtxtname.setText(add2);
                String add3=rs.getString("sbatch");
                jtxtbatch.setText(add3);
                String add4=rs.getString("sdep");
                jtxtdep.setText(add4);
                String add5=rs.getString("semail");
                jtxtemail.setText(add5);
                String add6=rs.getString("sphonenumber");
                jtxtcontactno.setText(add6);
                String add7=rs.getString("image");
                jLabel11.setIcon(ResizeImage2(add7));
               // jLabel11.setIcon(new javax.swing.ImageIcon(add7));
                rs.close();
               }
            else{
                JOptionPane.showMessageDialog(null, "The book id not found");
            }
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
            
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIDActionPerformed
//update form ....................................................................................
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jtxtID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No data to update");
            return ;
        }
        int action=JOptionPane.showConfirmDialog(null,"Do you really want to update ", "Update", JOptionPane.YES_OPTION);
        if(action==00){
            try{
                  Connect con=new Connect();
                String query="update student set regno='"+jtxtID.getText()
                +"',sname='"+jtxtname.getText()
                +"',sbatch ='"+jtxtbatch.getText()
                +"',sdep='"+jtxtdep.getText()
                +"',semail='"+jtxtemail.getText()
                +"',sphonenumber='"+jtxtcontactno.getText()
                +"',image='"+imgPath2
                +"' where regno='"+ jtxtID.getText()+"' ";
             
                con.setQuery(query);

                JOptionPane.showMessageDialog(null, "Updated the data");
            }catch(HeadlessException e){
                JOptionPane.showMessageDialog(null, e);
            }
            JTable1();
            clear2();
        }
    }//GEN-LAST:event_jButton5ActionPerformed
//table click send reg no to update form+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
              Connect con=new Connect();
            int row=jTable1.getSelectedRow();
            String table_click=(jTable1.getModel().getValueAt(row, 0).toString());
            String query="select * from student where regno='"+table_click+"'";
        
            rs=con.getQuery(query);
            if(rs.next()){
                String add1=rs.getString("regno");
                jtxtID.setText(add1);
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked
 //serch by name*******************************************************************************************
    private void jtxtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchNameKeyReleased
        // TODO add your handling code here:
        try{
              Connect con=new Connect();
            String query="select * from student where sname like '"+jtxtSearchName.getText()+"%'";
          
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchNameKeyReleased
     //serch by regno*******************************************************************************************
    private void jtxtSearchIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchIdKeyReleased
        // TODO add your handling code here:
        try{
              Connect con=new Connect();
            String query="select * from student where regno like '"+jtxtSearchId.getText()+"%'";
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchIdKeyReleased

    private void jtxtSearchDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchDepActionPerformed

    }//GEN-LAST:event_jtxtSearchDepActionPerformed
    //serch by department*******************************************************************************************
    private void jtxtSearchDepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchDepKeyReleased
        try{
              Connect con=new Connect();
            String query="select * from student where sdep like '"+jtxtSearchDep.getText()+"%'";
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchDepKeyReleased
// delete option***************************************************************************************************
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
     
        int action=JOptionPane.showConfirmDialog(null,"Do you really want to delete ", "delete", JOptionPane.YES_OPTION);
        if(action==00){
            try{
                  Connect con=new Connect();
                String query="delete from student where regno='"+jtxtID.getText()+"'";
               con.setQuery(query);
              

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
            JTable1();
        }
    }//GEN-LAST:event_jButton11ActionPerformed
    //insert the image+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.image","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile =file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel9.setIcon(ResizeImage(path));
            path=path.replace("\\", "/");
            imgPath=path;
        }
        else if(result==JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }    
    }//GEN-LAST:event_jButton3ActionPerformed
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon myImage=new ImageIcon(imgPath);
        Image img=myImage.getImage();
        Image newImage=img.getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImage);
        return image;
    }
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// update  the image****************************************************************************************
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          Connect con=new Connect();
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.image","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile =file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            jLabel11.setIcon(ResizeImage2(path));
            path=path.replace("\\", "/");
            imgPath2=path;
        }
        else if(result==JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton6ActionPerformed
     public ImageIcon ResizeImage2(String imgPath){
        ImageIcon myImage=new ImageIcon(imgPath);
        Image img=myImage.getImage();
        Image newImage=img.getScaledInstance(jLabel11.getWidth(),jLabel11.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImage);
        return image;
    }
//***************************************************************************************************************************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Year;
    private javax.swing.JLabel Year1;
    private javax.swing.JLabel Year2;
    private javax.swing.JLabel Year4;
    private javax.swing.JLabel Year5;
    private javax.swing.JLabel Year6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBatch;
    private javax.swing.JComboBox<String> jComboDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtContact;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtSearchDep;
    private javax.swing.JTextField jtxtSearchId;
    private javax.swing.JTextField jtxtSearchName;
    private javax.swing.JTextField jtxtbatch;
    private javax.swing.JTextField jtxtcontactno;
    private javax.swing.JTextField jtxtdep;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtname;
    // End of variables declaration//GEN-END:variables
}
