
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class Manageboook extends javax.swing.JInternalFrame {
   private DefaultTableModel dtm;
    ResultSet rs;
    /**
     * Creates new form Manageboook
     */
    public Manageboook() {
        initComponents();
        jTable1();
        Random();
    }
    //update automatic accsesing number
    public void Random(){
        Random rd=new Random();
        jtxtacc.setText("2017251"+rd.nextInt(100+1));    
    }
    // load table
    public void jTable1(){
            dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
        try{
             Connect con =new Connect();
            String query="select Accno,Bname,Bedition,Bpublisher,Bsection,Bpages from book";
           rs=con.getQuery(query);
           while(rs.next()){
            String accno=rs.getString("Accno");
            String Bname=rs.getString("Bname");
            String Bedition=rs.getString("Bedition");
            String Bpublisher=rs.getString("Bpublisher");
            String Bsection=rs.getString("Bsection");
            String Bpages=rs.getString("Bpages");
            
            dtm.addRow(new Object[]{accno,Bname,Bedition,Bpublisher,Bsection,Bpages});
            
            
           }
            
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
        
    }
    //reset
    public void clear2(){
        jtxtPub.setText("");
        jtxtPages.setText("");
        jtxtName.setText("");
        jtxtSection.setText("");
        jcomboEdi.setSelectedItem(0);
        
    }
    //reset
      public void clear(){
        jtxtname.setText("");
        jtxtedi.setText("");
        jtxtpub.setText("");
        jtxtsection.setText("");
        jtxtpages.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtacc = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jcomboEdi = new javax.swing.JComboBox<>();
        jtxtPub = new javax.swing.JTextField();
        jtxtSection = new javax.swing.JTextField();
        jtxtPages = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jlblName = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblEdi = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jlblPages = new javax.swing.JLabel();
        jlblPub = new javax.swing.JLabel();
        jtxtedi = new javax.swing.JTextField();
        jtxtAcc = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtpages = new javax.swing.JTextField();
        jtxtsection = new javax.swing.JTextField();
        jtxtpub = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jtxtSearchName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtSearchAccno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtSearchSection = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setResizable(true);
        setTitle("ManageBook");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Accession no");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Edition");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Publisher");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Section");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Pages");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jtxtacc.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jtxtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtaccKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 230, -1));

        jtxtName.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });
        jtxtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNameKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 270, -1));

        jcomboEdi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcomboEdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Edition", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        jPanel2.add(jcomboEdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 270, -1));

        jtxtPub.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jtxtPub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPubKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 270, -1));

        jtxtSection.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jtxtSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSectionKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 270, -1));

        jtxtPages.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jtxtPages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPagesKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 270, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.setMaximumSize(new java.awt.Dimension(67, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(67, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(67, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 70, 30));

        jTabbedPane1.addTab("Add Book", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Acc. No");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Edition");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Publisher");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Section");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Pages");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_icon-101-folder-search_314467 (3).png"))); // NOI18N
        jButton4.setToolTipText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 60, 30));

        jlblName.setBackground(new java.awt.Color(255, 255, 255));
        jlblName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 109, 260, -1));

        jlblID.setBackground(new java.awt.Color(255, 255, 255));
        jlblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 74, 258, -1));

        jlblEdi.setBackground(new java.awt.Color(255, 255, 255));
        jlblEdi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblEdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 137, 260, -1));

        jlblPrice.setBackground(new java.awt.Color(255, 255, 255));
        jlblPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 201, 263, -1));

        jlblPages.setBackground(new java.awt.Color(255, 255, 255));
        jlblPages.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 233, 263, -1));

        jlblPub.setBackground(new java.awt.Color(255, 255, 255));
        jlblPub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jlblPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 169, 263, -1));

        jtxtedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtedi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtediKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 280, -1));

        jtxtAcc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAccActionPerformed(evt);
            }
        });
        jtxtAcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtAccKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 210, 30));

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnameKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 280, -1));

        jtxtpages.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtpages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpagesKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 280, -1));

        jtxtsection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtsection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsectionKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 280, -1));

        jtxtpub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtpub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpubActionPerformed(evt);
            }
        });
        jtxtpub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpubKeyReleased(evt);
            }
        });
        jPanel3.add(jtxtpub, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 280, -1));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 80, 30));

        jTabbedPane1.addTab("Edit Book", jPanel3);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accession No", "Book Name", "Edition", "Publisher", "Section", "Pages"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 540, 300));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Name:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jtxtSearchName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchNameKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Acc. No:");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jtxtSearchAccno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchAccno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchAccnoKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchAccno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 30));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Section:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jtxtSearchSection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtSearchSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtSearchSectionKeyReleased(evt);
            }
        });
        jPanel7.add(jtxtSearchSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 80, 30));

        jButton11.setBackground(new java.awt.Color(204, 204, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Delete");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jButton11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton11KeyReleased(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 70, -1));

        jTabbedPane1.addTab("Search Book", jPanel7);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 400));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed
    //reset by reset button************---------------------------------------------------------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jtxtacc.setText("");
        jtxtName.setText("");
        jtxtPub.setText("");
        jtxtSection.setText("");
        jtxtPages.setText("");
        jcomboEdi.setSelectedIndex(0);

    }//GEN-LAST:event_jButton1ActionPerformed
//insert the data by buttin+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Connect con = new Connect();
            String query="insert into book(Accno,Bname,Bedition,Bpublisher,Bsection,Bpages)  values('"+jtxtacc.getText()
                    +"','"+jtxtName.getText()
                    +"','"+jcomboEdi.getSelectedItem()
                    +"','"+jtxtPub.getText()
                    +"','"+jtxtSection.getText()
                    +"','"+jtxtPages.getText()
                    +"')";
            if (jtxtName.getText().equals("")||jtxtPub.getText().equals("")||jtxtSection.getText().equals("")||jtxtPages.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill the every details");
                return;
            }
            
            con.setQuery(query);
            JOptionPane.showMessageDialog(null, "New Bokk Added");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"A Book have already accession number ");
        }
        jTable1();
        clear2();
        Random();

    }//GEN-LAST:event_jButton2ActionPerformed
//search button/////////////////////////////////////////////////////////////////////////////////////////////////////
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            Connect con= new Connect();
            String query="Select * from book where Accno='"+jtxtAcc.getText()+"' ";
            rs=con.getQuery(query);
            if(rs.next()){
                String add1=rs.getString("Bname");
                jtxtname.setText(add1);
                String add3=rs.getString("Bedition");
                jtxtedi.setText(add3);
                String add4=rs.getString("Bpublisher");
                jtxtpub.setText(add4);
                String add5=rs.getString("Bsection");
                jtxtsection.setText(add5);
                String add6=rs.getString("Bpages");
                jtxtpages.setText(add6);
            }
          else{
                JOptionPane.showMessageDialog(null, "The book id not found");
            }
           
            
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
//update button*********************************************************************************************************
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jtxtAcc.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No data to update");
            return ;
        }
        int action=JOptionPane.showConfirmDialog(null,"Do you really want to update ", "Update", JOptionPane.YES_OPTION);
        if(action==00){
            try{
                Connect con=new Connect();
                String query="update book set Accno='"+jtxtAcc.getText()
                +"',Bname='"+jtxtname.getText()
                +"',Bedition ='"+jtxtedi.getText()
                +"',Bpublisher='"+jtxtpub.getText()
                +"',Bsection='"+jtxtsection.getText()
                +"',Bpages='"+jtxtpages.getText()+"' where Accno='"+ jtxtAcc.getText()+"' ";
               
                con.setQuery(query);

                JOptionPane.showMessageDialog(null, "Updated the data");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            jTable1();
            clear();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            Connect con =new Connect();
            int row=jTable1.getSelectedRow();
            String table_click=(jTable1.getModel().getValueAt(row,0).toString());
            String query=" select * from book where Accno='"+table_click+"' ";
           
            rs=con.getQuery(query);
            if(rs.next()){
                String add1=rs.getString("Accno");
                jtxtAcc.setText(add1);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jTable1MouseClicked
//search option*---------------------------------------------------------------------------------------------------------------
    private void jtxtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchNameKeyReleased
        try{
            Connect con= new Connect();
            String query="select * from book where Bname like '"+jtxtSearchName.getText()+"%'";
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchNameKeyReleased

    private void jtxtSearchAccnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchAccnoKeyReleased
        try{
            Connect con= new Connect();
            String query="select * from book where Accno like '"+jtxtSearchAccno.getText()+"%'";
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchAccnoKeyReleased

    private void jtxtSearchSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSearchSectionKeyReleased
        try{
            Connect con= new Connect();
            String query="select * from book where Bsection like '"+jtxtSearchSection.getText()+"%'";
     
            rs=con.getQuery(query);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jtxtSearchSectionKeyReleased
//----------------------------------------------------------------------------------------------------------
    // delete by table selected************************************************************************************
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int action=JOptionPane.showConfirmDialog(null,"Do you really want to delete ", "delete", JOptionPane.YES_OPTION);
        if(action==00){
            try{
                 Connect con = new Connect();
                String query = "delete from book where Accno='" + jtxtAcc.getText() + "'";
                con.setQuery(query);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            jTable1();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtxtaccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtaccKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtName.requestFocus();
        }
    }//GEN-LAST:event_jtxtaccKeyReleased

    private void jtxtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNameKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtPub.requestFocus();
        }
    }//GEN-LAST:event_jtxtNameKeyReleased

    private void jtxtSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSectionKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtPages.requestFocus();
        }
    }//GEN-LAST:event_jtxtSectionKeyReleased

    private void jtxtPubKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPubKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtSection.requestFocus();
        }
    }//GEN-LAST:event_jtxtPubKeyReleased

    private void jtxtPagesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPagesKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jtxtPagesKeyReleased

    private void jtxtAccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAccKeyReleased
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtname.requestFocus();
        }
    }//GEN-LAST:event_jtxtAccKeyReleased

    private void jtxtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnameKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtedi.requestFocus();
        }
    }//GEN-LAST:event_jtxtnameKeyReleased

    private void jtxtediKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtediKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtpub.requestFocus();
        }
    }//GEN-LAST:event_jtxtediKeyReleased

    private void jtxtpubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpubActionPerformed

    private void jtxtpubKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpubKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtsection.requestFocus();
        }
    }//GEN-LAST:event_jtxtpubKeyReleased

    private void jtxtsectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsectionKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jtxtpages.requestFocus();
        }
    }//GEN-LAST:event_jtxtsectionKeyReleased

    private void jtxtpagesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpagesKeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton5.requestFocus();
        }
    }//GEN-LAST:event_jtxtpagesKeyReleased

    private void jButton11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton11KeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
        int action=JOptionPane.showConfirmDialog(null,"Do you really want to delete ", "delete", JOptionPane.YES_OPTION);
        if(action==00){
            try{
                 Connect con = new Connect();
                String query = "delete from book where Accno='" + jtxtAcc.getText() + "'";
                con.setQuery(query);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            jTable1();
        }
 
        }
    }//GEN-LAST:event_jButton11KeyReleased

    private void jtxtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcomboEdi;
    private javax.swing.JLabel jlblEdi;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPages;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblPub;
    private javax.swing.JTextField jtxtAcc;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPages;
    private javax.swing.JTextField jtxtPub;
    private javax.swing.JTextField jtxtSearchAccno;
    private javax.swing.JTextField jtxtSearchName;
    private javax.swing.JTextField jtxtSearchSection;
    private javax.swing.JTextField jtxtSection;
    private javax.swing.JTextField jtxtacc;
    private javax.swing.JTextField jtxtedi;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtpages;
    private javax.swing.JTextField jtxtpub;
    private javax.swing.JTextField jtxtsection;
    // End of variables declaration//GEN-END:variables
}
