
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class notifictionCenter extends javax.swing.JInternalFrame {
    int count;
    DefaultTableModel dtm;
    
    public notifictionCenter() {
        initComponents();
        calEmail();
        checkcon();
    }
    
    
    //Check connection>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.
    public void checkcon(){
        try {       
            try {
        	URL url = new URL("http://www.google.com");
        	//System.out.println(url.getHost());
		HttpURLConnection con = (HttpURLConnection) url.openConnection();
                con.connect();
		if (con.getResponseCode() == 200){
		System.out.println("Connection established!!");
                lblconnection.setText("Connection established!!");				}
            } catch (Exception exception) {
                System.out.println("No Connection");
                lblconnection1.setText("No Connection");
            }
	} catch (Exception e) {
            e.printStackTrace();
	}
	
    }
    
     //Calculate who are not handover the books*********************************************************
      public void calEmail(){
          dtm=(DefaultTableModel)jTable1.getModel();
          
          Connect con2=new Connect();
          String query2="select id from issuebook where id=(select MAX(id) from issuebook)";
          ResultSet rs2=con2.getQuery(query2);
        try {
            if(rs2.next()){
               count = rs2.getInt("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        try{
        
            for (int i=0; i <=count; i++) { 
            Connect con=new Connect();
            String query="select SName,ReturnDate,Issuedate,SRegno,BName,SEmail from issuebook where id='"+i+"'";
            ResultSet rs=con.getQuery(query);
           
            if(rs.next()){
                String issueDate=rs.getString("Issuedate");
                String ReturnDate=rs.getString("ReturnDate");
                String[] ReturnDatea = ReturnDate.split("/");
                String[] IssueDatea = issueDate.split("/");
                
                String year = ReturnDatea[0];
                String month = ReturnDatea[1]+ReturnDatea[2];
                String month2=IssueDatea[1]+IssueDatea[2];
                
                int x=Integer.parseInt(month);
                int y=Integer.parseInt(month2);
                int result=x-y;
                
                if(result==2 || result==1){
                   String name=rs.getString("SName");
                    String regno=rs.getString("SRegno");
                     String email=rs.getString("SEmail");
                //  txtnoti.setText( name +" has not yet been handerd over the book Can I inform to him");
                
                dtm.addRow(new Object[]{regno,name,email});
                }
              
            }
          }
          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
         
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblconnection = new javax.swing.JLabel();
        lblconnection1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblnoti = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Notifications ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        lblconnection.setBackground(new java.awt.Color(255, 255, 255));
        lblconnection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblconnection.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(lblconnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 11, 175, 22));

        lblconnection1.setBackground(new java.awt.Color(255, 255, 255));
        lblconnection1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblconnection1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblconnection1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 10, 156, 22));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 731, 40));

        lblnoti.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lblnoti.setForeground(new java.awt.Color(153, 0, 0));
        lblnoti.setText("This Students has not yet received the books Please send email to remainder");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registertion no", "Name", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblnoti)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoti, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 730, 370));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setBackground(new java.awt.Color(102, 102, 102));
        txtemail.setBorder(null);
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 242, -1));

        txtname.setBackground(new java.awt.Color(102, 102, 102));
        txtname.setBorder(null);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 731, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
//***************************** send email ****************
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(lblconnection.getText()=="Connection established!!"){
        sendemail x=new sendemail();
      try{
          x.email(txtemail.getText(),txtname.getText());
          JOptionPane.showMessageDialog(null, "message sent successfully...");
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
      }
      }else{
          JOptionPane.showMessageDialog(null, "Connection Faild");
          
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed
//table click to send email************************************************************************************************
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
              Connect con=new Connect();
            int row=jTable1.getSelectedRow();
            String table_click=(jTable1.getModel().getValueAt(row, 0).toString());
            String query="select * from student where regno='"+table_click+"'";
        
            ResultSet rs=con.getQuery(query);
            if(rs.next()){
                String add1=rs.getString("semail");
                txtemail.setText(add1);
                String add2=rs.getString("sname");
                txtname.setText(add2);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
    }//GEN-LAST:event_txtnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblconnection;
    private javax.swing.JLabel lblconnection1;
    private javax.swing.JLabel lblnoti;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
