
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasintha
 */
public class Statistics extends javax.swing.JInternalFrame {
    Connect con=new Connect ();
    ResultSet rs;
    private DefaultTableModel dtm;
    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        this.setLocation(50, 25);
        Table1();
        Table2();
    }

     private void Table1(){
         dtm=(DefaultTableModel)jTableissue.getModel();
        try{
            String query="select SRegno,SName,Accno,BName,ReturnDate,Issuedate from issuebook";
            rs=con.getQuery(query);
            while(rs.next()){
                String StuName=rs.getString("SName");
                String StuRegNo=rs.getString("SRegno");
               
                String AccNo=rs.getString("Accno");
                String BookName=rs.getString("BName");
                String Issuedate=rs.getString("Issuedate");
                String AcceptableDate=rs.getString("ReturnDate");
               
                dtm.addRow(new Object[]{StuName,StuRegNo,AccNo,BookName,Issuedate,AcceptableDate});
                
            }

        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void Table2(){
        dtm=(DefaultTableModel)jTablereturn.getModel();
        try{
            String query="select SRegno,SName,Accno,BName,Issuedate,Returndate from returnbook";
           rs=con.getQuery(query);
            while(rs.next()){
                String StuName=rs.getString("SName");
                String StuRegNo=rs.getString("SRegno");
               
                String AccNo=rs.getString("Accno");
                String BookName=rs.getString("BName");
                String Issuedate=rs.getString("Issuedate");
                String AcceptableDate=rs.getString("ReturnDate");
               
                dtm.addRow(new Object[]{StuName,StuRegNo,AccNo,BookName,Issuedate,AcceptableDate});
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableissue = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablereturn = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Statistics");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jTableissue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student RegNo", "Accession No", "Book Name", "Issue Date", "Acceptable Date"
            }
        ));
        jScrollPane1.setViewportView(jTableissue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Issue Details", jPanel1);

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        jTablereturn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Student RegNo", "Accession No", "Book Name", "Issue Date", "Return Date"
            }
        ));
        jTablereturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablereturnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablereturn);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Return Details", jPanel6);

        jPanel4.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1040, 420));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Return Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Issue Reports");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/if_statistics_383213.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablereturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablereturnMouseClicked

    }//GEN-LAST:event_jTablereturnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Report x=new Report();
       x.generateReport("Blank_A4_Landscape_1.jrxml", null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Report x=new Report();
       String report="C:/Users/Hasintha/Desktop/New folder (2)/e.png";
       x.generateReport("Blank_A4_Landscape.jrxml",null);
       
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableissue;
    private javax.swing.JTable jTablereturn;
    // End of variables declaration//GEN-END:variables
}
